baseURL = 'https://kobimedrish.com/'
languageCode = 'en-us'
title = "~/kobi-medrish"
theme = "papermod"

buildDrafts = false

pygmentsUseClasses = true
enableRobotsTXT = true

[outputs]

  # HTML: for normal website.
  # RSS: an XML feed, index.xml.
  # JSON: for search.
  home = ["HTML", "RSS", "JSON"]
[services]
  [services.googleAnalytics]
    ID = "G-0RK8S4HNWH"

[params]
  ShowShareButtons = true
  ShareButtons = ["twitter", "linkedin", "facebook", "reddit", "whatsapp", "telegram"]
  defaultTheme = "dark"
  disableThemeToggle = false
  disableSpecial1stPost = true
  hidemeta = false
  favicon = "favicon.png"
  comments = false
  showtoc = true
  tocopen = false
  ShowCodeCopyButtons = true
  description = "Kobi Medrish's blog on software development, Linux systems, DevOps, real-time systems, and modern programming practices. Covering topics like C/C++, Python, Bash, CI/CD, NixOS, microservices, ebike."
  author = "Kobi Medrish"
  keywords = [
    "C", "C++", "Python", "Bash", "Cmake", "Linux", "Yocto", "Real Time", "ARM", "x86", "x64",
    "Firmware", "CI/CD", "Ansible", "nix", "Gtest", "Catch2", "Valgrind", "Sanitizers", "gdb",
    "kmemleak", "Doxygen", "KVM", "VirtualBox", "Docker", "Encryption", "SSH", "GPG", "OpenSSL",
    "Blockchain", "microservices", "Clean Code", "SOLID", "Design Patterns", "OOP", "git",
    "Networking", "Multithreading", "IPC", "Data Structures", "NixOS", "i3wm", "zsh", "tmux",
    "neovim", "Emacs", "Autodidact"
  ]

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  [params.socialAccounts]
    twitter = { username = "kmedrish" }

  [params.homeInfoParams]
    # Title = "Welcome"
    Content = """
Hi, I am an embedded software developer, tinkerer, and a generalist.

> "A human being should be able to change a diaper, plan an invasion, butcher a hog, conn a ship, design a building, write a sonnet, balance accounts, build a wall, set a bone, comfort the dying, take orders, give orders, cooperate, act alone, solve equations, analyze a new problem, pitch manure, program a computer, cook a tasty meal, fight efficiently, die gallantly.
> <br><br>
> **Specialization is for insects**"
>
> â€” Robert A. Heinlein.
"""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/p3t33"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/Kmedrish"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kmedrish"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[minify]
  disableXML = false
  minifyOutput = true

[menu]
  [[menu.main]]
    identifier = "books"
    name = "books recommendations"
    url = "/books/"
    weight = 10

  [[menu.main]]
    identifier = "search"
    name = "search"
    url = "/search/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
